config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'history', to: 'pages#history', as: :history

  get 'rice', to: 'crops#rice', as: :rice
  get 'wheat', to: 'crops#wheat', as: :wheat
  get 'corn', to: 'crops#corn', as: :corn

  resources :resources, only: [:index, :show]

  resources :recipes, only: :index do
    collection do
      get :rice
      get :wheat
      get :corn
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/crop.rb
class Crop < ApplicationRecord
end

app/models/recipe.rb
class Recipe < ApplicationRecord
end

app/models/resource.rb
class Resource < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/crops_controller.rb
class CropsController < ApplicationController
  def rice
  end

  def wheat
  end

  def corn
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def history
  end
end

app/controllers/recipes_controller.rb
require 'nokogiri'
require 'open-uri'
require 'amazing_print'

class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
    # @recipes = @recipes.where(cereal: params[:cereal]) if params[:cereal].present?
  end

  def rice
    url = 'https://www.allrecipes.com/search/?wt=rice'
    doc = Nokogiri::HTML(open(url), nil, 'utf-8')
    @recipes = doc.search('.fixed-recipe-card').first(12).map do |element|
      {
        name: element.search('span.fixed-recipe-card__title-link').text,
        description: element.search('.fixed-recipe-card__description').text,
        image_url: element.search('.fixed-recipe-card__img').attr('data-original-src').text,
        url: element.search('a.fixed-recipe-card__title-link').attr('href').text,
        cereal: 'rice'
      }
    end
    @display_result = @recipes.map do |recipe| {
      card: render_to_string(partial: 'recipe_card', locals: { recipe: recipe })
    }
    end
    render json: @display_result.to_json
  end

  def wheat
    url = 'https://www.allrecipes.com/search/?wt=wheat'
    doc = Nokogiri::HTML(open(url), nil, 'utf-8')
    @recipes = doc.search('.fixed-recipe-card').first(12).map do |element|
      {
        name: element.search('span.fixed-recipe-card__title-link').text,
        description: element.search('.fixed-recipe-card__description').text,
        image_url: element.search('.fixed-recipe-card__img').attr('data-original-src').text,
        url: element.search('a.fixed-recipe-card__title-link').attr('href').text,
        cereal: 'wheat'
      }
    end
    @display_result = @recipes.map do |recipe| {
      card: render_to_string(partial: 'recipe_card', locals: { recipe: recipe })
    }
    end
    render json: @display_result.to_json
  end

  def corn
    url = 'https://www.allrecipes.com/search/?wt=corn'
    doc = Nokogiri::HTML(open(url), nil, 'utf-8')
    @recipes = doc.search('.fixed-recipe-card').first(12).map do |element|
      {
        name: element.search('span.fixed-recipe-card__title-link').text,
        description: element.search('.fixed-recipe-card__description').text,
        image_url: element.search('.fixed-recipe-card__img').attr('data-original-src').text,
        url: element.search('a.fixed-recipe-card__title-link').attr('href').text,
        cereal: 'corn'
      }
    end
    @display_result = @recipes.map do |recipe| {
      card: render_to_string(partial: 'recipe_card', locals: { recipe: recipe })
    }
    end
    render json: @display_result.to_json
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :description, :image_url, :url, :cereal)
  end
end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController
  def index
    @resources = Resource.all

    @resources = @resources.where(resource_type: params[:resource_type]) if params[:resource_type].present?
  end

  private

  def resource_params
    params.require(:resource).permit(:title, :author, :language, :url, :resource_type)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cerial Eater</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/resources/_resources_results.html.erb
<% @resources.each do |resource| %>
  <% if resource[:resource_type] == "book" %>
  <div class="m-8 lg:m-4 p-8 lg:p-4 bg-white-light text-xl lg:text-sm tracking-wider flex items-center rounded-sm">
    <div class="flex items-center mr-6"><p class="p-2 text-base lg:text-xs uppercase font-light bg-white-dark"><%= resource[:language] %></p></div>
    <div class="tracking-wider">
      <p class="uppercase font-medium"><%= resource[:title] %></p>
      <p class="font-light"><%= resource[:author] %></p>
    </div>
  </div>
  <% else %>
  <div class="m-8 lg:m-4 p-8 lg:p-4 bg-white-light text-xl lg:text-sm tracking-wider flex items-center rounded-sm">
    <div class="flex items-center mr-6"><p class="p-2 text-base lg:text-xs uppercase font-light bg-white-dark"><%= resource[:language] %></p></div>
    <div class="font-medium uppercase tracking-wider">
      <p><%= resource[:title] %></p>
      <p class="text-xl lg:text-base">🎬 <a href="<%= resource[:url] %>" class="ml-4 uppercase tracking-wider underline" target="_blank">Watch here</a></p>
    </div>
  </div>
  <% end %>
<% end  %>

app/views/resources/index.html.erb
<div class="m-12 lg:m-0 bg-fixed bg-cover bg-center bg-resources bg-no-repeat h-screen lg:h-auto flex flex-col">

<div class="lg:mx-56">
  <h1 class="pt-24 lg:pt-10 text-center text-7xl lg:text-4xl font-display text-white-light font-bold">Cerial Resources</h1>
  <div class="p-8 w-full text-2xl lg:text-lg text-center text-white-light tracking-wider">
    <p>Resources to yield some more <span class="font-bold">seeds of ideas</span> into our mind</p>
  </div>

<!-- Resources menu -->
  <div class="mb-8 lg: mx-72 px-16 flex justify-around">
    <%= link_to 'Books', resources_path(resource_type: 'book'), class:"py-1 px-10 flex items-center border-4 border-white-light border-opacity-100 rounded-full text-3xl lg:text-xl text-white-light font-display" %>
    <%= link_to 'Documentaries', resources_path(resource_type: 'documentary'), class:"py-1 px-10 flex items-center border-4 border-white-light border-opacity-100 rounded-full text-3xl lg:text-xl text-white-light font-display" %>
  </div>

<!-- Resources results -->
  <div class="flex-1 overflow-y-auto lg:grid lg:grid-cols-3 lg:gap-4">
    <%= render 'resources_results', resources: @resources %>
  </div>
</div>


<!-- Homepage button -->
  <div class="py-12 flex justify-center">
    <%= link_to 'Homepage', root_path, class: "text-2xl xl:text-base text-white-light hover:text-white-darker" %>
    <div class="ml-3 xl:ml-1 w-6 xl:w-3 transform rotate-12 flex content-center">
      <svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 30 51"><path d="M21.696 12.648a8.984 8.984 0 00-4.066 4.136l1.35-4.105a9.052 9.052 0 003.692-12L22.329 0l-.641.324a9.053 9.053 0 00-4.177 11.792l-1.288 3.918a9.065 9.065 0 00-6.116-9.988l-.682-.224-.237.723a9.065 9.065 0 005.773 11.43l.563.185-2.208 6.719a9.052 9.052 0 00-6.121-9.973l-.682-.224-.238.723a9.065 9.065 0 005.774 11.43l.563.184-2.209 6.719a9.051 9.051 0 00-6.12-9.973l-.683-.224-.237.723a9.065 9.065 0 005.773 11.43l.563.184-2.209 6.72a9.052 9.052 0 00-6.12-9.972L.688 32.4l-.238.723a9.065 9.065 0 005.774 11.43l.563.185-1.496 4.55a.785.785 0 001.492.49l1.496-4.55.605.2a9.055 9.055 0 0011.43-5.775l.237-.722-.682-.225a9.053 9.053 0 00-10.977 4.657l2.3-6.994.604.198a9.056 9.056 0 0011.43-5.774l.237-.723-.681-.224a9.053 9.053 0 00-10.978 4.656l2.3-6.994.605.199a9.055 9.055 0 0011.43-5.774l.237-.722-.682-.224a9.053 9.053 0 00-10.977 4.656l2.3-6.994.604.199a9.055 9.055 0 0011.43-5.774l.238-.722-.682-.225a8.995 8.995 0 00-6.91.52z" fill="#fff"/></svg>
    </div>
  </div>
</div>